sudo: required
services:
  - docker
language: python
python:
  - "2.7"
env:
  global:
    # Docker
    - DOCKER_REPOSITORY=mozmeao/cloudflare-datadog
    - DOCKER_USERNAME="moztravis"
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
  - pip install flake8
before_script:
  - env > .env
script:
  - flake8 .
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .
deploy:
  - provider: script
    script: bin/push-to-dockerhub.sh
    on:
      branch: master
      repo: mozmeao/cloudflare-datadog
